### ISSUE TITLE
Can not work normally

### ISSUE THREAD

**Issue by aihk** [eyalabraham/ps2mac#3]
After I compile it, the PS2 keyboard does not work properly. Can you provide a compiled firmware?

**Comment by eyalabraham** [comment]
@aihk please describe what the symptoms are. For example:

- Do you see the PS2 keyboard lights on one by one (which is a test patterns I coded) or nothing at all? if nothing lights up on the PS2 keyboard then first check PS2 side wiring; check wiring on the Mac side for correct power lead polarity.
- Do you see characters on the Mac when you type but they are wrong of sometimes do not appear? if you see nothing on the Mac check Mac Plus side wiring into the RJ connector Data and Clock.
- Does your AVR programmer indicate successful programming?
- Did you pull the AVR reset line (pin 1) with a resistor to HI?

Any detailed description of the symptoms will help.

**Comment by aihk** [comment]
When the MAC is turned on, the three LEDs on the keyboard will light up and then turn off. Both clock and data should be correct. pin1 doesn't have any resistor, is 10K resistor ok? Is it connected to +5V?

**Comment by aihk** [comment]
Pin1 is connected to +5v with a 10k resistor. When starting the mac, after the indicator lights of the keyboard flash alternately, an indicator light will finally light up. There are still no characters in the mac input.

**Comment by eyalabraham** [comment]
@aihk yes, the NumLock then CapsLock then ScrollLock lights will turn on sequentially and then they should be **_all off_**. This is part of the initialization sequence. The resistor for pin 1 (reset) could be 10k to +5v as you described. The internal pull-up is actually enabled, but an external pull-up  is just a precaution.

Since the LEDs light up then the PS2 interface side seems to work. If you're not seeing characters on the MAC you might have a wiring problem between the AVR and the MAC, I'd double check just in case: connection, swapped data/clock etc.

One more thing to double check is the Mac Model, I assume you are trying this on a Mac Plus and that the Mac's keyboard port is not faulty.

You can download the compiled code [from my Google drive here](https://drive.google.com/file/d/1jx2m8XhreFDSqx2zarS19wLtnh33quRe/view?usp=sharing). Although if your wiring etc is at fault I don't think this will help.

**Comment by aihk** [comment]
Found the reason, it's my keyboard. The keyboard of the AT-XT switching protocol cannot be used. After I replaced the simple PS2 keyboard, it was normal.
